### PR TITLE
Check if the field has name set, not title or key

### PR DESCRIPTION
**Pull request by rvsia**
- [x] check only name in validators
- [x] remove keys from all examples and included schemas
- [x] remove keys logic from all components

### CODE REVIEW

**Comment by rvsia** [comment]
@Hyperkid123 Quick question before removing WIP: Should be it a feat or fix? It can break some forms...

**Comment by Hyperkid123** [comment]
@rvsia fix

**Comment by rvsia** [comment]
@Hyperkid123 done! :green_apple:

**Pull request merged**
