### PR TITLE
Add validateOnMount option

### PR DESCRIPTION
**Pull request by fhlavac**
**Description**

Adds validateOnMount option to PF4 mapper.

**Schema** 

```
          schema={{
              fields: [
                {
                  name: 'textarea_box_1',
                  label: 'Text Area',
                  title: 'Text Area',
                  validate: [
                    {
                      type: validators.PATTERN,
                      pattern: '[0-9]'
                    }
                  ],
                  validateOnMount: true,
                  component: components.TEXTAREA
                }
              ]
          }}

```
@Hyperkid123

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
@fhlavac this commit should not be listed: Release of new version: 2.22.0 <no> [skip ci]. Please remove it.

**Review by rvsia — COMMENTED** [review]
Can you please include test files? You can use the same as in the other mappers that are using validateOnMount.

**Comment by rvsia** [comment]
@fhlavac thanks for the test file, however more important is to test the behavior of components.

You can basically use this one https://github.com/data-driven-forms/react-forms/blob/1a29b9063ab940bb3d2822cd917ab3220376f80a/packages/ant-component-mapper/src/tests/components.test.js#L129

In PF4 there is form-fields-test.

**Comment by fhlavac** [comment]
Oh, missed that, I'll add it. Thank you :-)

**Comment by fhlavac** [comment]
@rvsia tests should be enhanced

**Comment by rvsia** [comment]
@fhlavac Thank you very much!

**Review by rvsia — APPROVED** [review]

**Pull request merged**
