### PR TITLE
Fix MUI imports in demo

### PR DESCRIPTION
**Pull request by rvsia**
- ExapnsionPanel was renamed to Accordion

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
How come this just happened? Wasn't there a lock file with older mui version?

**Comment by rvsia** [comment]
@Hyperkid123  there is just a polite warning in the console log... and it has been there for some time :smile_cat:

**Comment by Hyperkid123** [comment]
:cake:

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
