### PR TITLE
fix(pf3select): props options was overwriting state

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

Empty props was overwriting state when async options.. because of new repo, it is not possible to track when it got broken. :ghost: 

Thanks @andyvesel for reporting!

### CODE REVIEW

**Comment by andyvesel** [comment]
@rvsia thanks! :+1: 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1727920

**Comment by aufi** [comment]
> @rvsia thanks! 
> Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1727920

Hi, we need update https://github.com/ManageIQ/manageiq-ui-classic/blob/ivanchuk/yarn.lock in Ivanchuk branch in order to get it fixed.

**Comment by Hyperkid123** [comment]
@aufi can you create BZ and assign in to me (mmarosi@redhat.com). Or i can create it myself if you prefer.

**Comment by aufi** [comment]
@Hyperkid123 I believe this should be part of https://bugzilla.redhat.com/show_bug.cgi?id=1727920 whic has been moved to ON_DEV due to pending update of yarn.lock. Thanks a lot!

**Comment by Hyperkid123** [comment]
@aufi ok

**Comment by aufi** [comment]
@Hyperkid123 I believe this should be part of https://bugzilla.redhat.com/show_bug.cgi?id=1727920 which has been moved back to ON_DEV due to pending update of yarn.lock. Thanks a lot!

**Pull request merged**
