### PR TITLE
fix(pf4,suir): Make sort icons consistent among all dual-list selectors

### PR DESCRIPTION
**Pull request by boaz0**
This is a nit change I was asked to do by @nlcwong 

Screenshot_2020-06-09 Data driven forms(1)

Screenshot_2020-06-09 Data driven forms

//cc @rvsia @Hyperkid123

### CODE REVIEW

**Comment by rvsia** [comment]
@boaz0 Could you please attach Before screenshots? To be honest, I cannot tell the difference. :smile_cat:

**Comment by boaz0** [comment]
Yeah sure!

**Comment by boaz0** [comment]
@rvsia these are the main changes.
In PF4 mapper these icons were used:

image

image

And I changed it to:

image

image

I also noticed that Semantic UI is using arrow icons for sorting:

image

image

and I changed it to:

image

image

I hope that was helpful enough. If you rather me show a diff between the screenshots that's fine too.

**Comment by rvsia** [comment]
@boaz0 oh, this is great! Thanks!

**Comment by Hyperkid123** [comment]
@boaz0 nice. Can you check the layout on smaller screens? I think it's likely that eventually, it will have to be fixed anyway.

**Comment by boaz0** [comment]
@Hyperkid123 is it possible to do it from you laptop using firefox or I need to use my mobile?

**Comment by Hyperkid123** [comment]
@boaz0 just shrink the screen

**Comment by boaz0** [comment]
output

@Hyperkid123

**Comment by Hyperkid123** [comment]
@boaz0 perfect! One more thing I would do is align the buttons next to each other right after the sections stack on each other. I see a small period where the icons point in the right direction but the buttons are still in a column instead of in a row.

**Comment by boaz0** [comment]
output
@Hyperkid123

**Comment by boaz0** [comment]
Thank ya'all @Hyperkid123 @rvsia

**Pull request merged**
