### PR TITLE
fix(renderer): onCancel receives form values

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

onCancel now receives `values`

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia we will have to wait for the CI to wake up.

**Comment by rvsia** [comment]
@Hyperkid123 In CircleCI `Build forked pull requests` was turned off.. so yeah, we would wait forever. 🔮 😃

**Comment by Hyperkid123** [comment]
@rvsia and PF3 also did some updates. One more snapshot

**Comment by rvsia** [comment]
@Hyperkid123 Yean and another snapshot failed this morning... please, merge this ASAP :pray: :dagger:

**Pull request merged**
