### PR TITLE
fix(pf3): date-time picker input format.

### LINKED ISSUE #184: Allow date-time picker input formatting
Allow users to set format `yyDDmmmm` for example for the picker input.

### PR DESCRIPTION
**Pull request by Hyperkid123**
closes #184

### CODE REVIEW

**Comment by rvsia** [comment]
@Hyperkid123 Docs update :book: :fire:

**Comment by Hyperkid123** [comment]
cc @skateman

**Comment by skateman** [comment]
@Hyperkid123 I don'y really need this in ddf-editor for now, so good for me.

**Pull request merged**
