### PR TITLE
fix(doc): Fix minor typo

### PR DESCRIPTION
**Pull request by nclavaud**
**Description**

Fix minor typo in schema doc.

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]
:heart:

**Review by rvsia — APPROVED** [review]

**Comment by rvsia** [comment]
@nclavaud Hello and thanks for the PR!

Can you just please change the commit message - we don't use Semantic release for the documentation so there is no reason to use the specific message format (in the other case, it would release new versions of all packages). Changing it to `Fix minor typo in docs` would be sufficient. Thanks!

**Comment by nclavaud** [comment]
Of course! Commit message has just been updated :-)

**Pull request merged**
