### PR TITLE
fix(manager): allow multiple field listener validators

### PR DESCRIPTION
**Pull request by Hyperkid123**
part of https://github.com/data-driven-forms/react-forms/issues/739

I have added `composeValidators` but then I have realized, it's not usable for this feature. I have not added test but we will need this function later anyway.

### CODE REVIEW

**Review by rvsia — COMMENTED** [review]
Can you please add test cases?

```jsx
registerField({name: 'field', validate: fn1})
registerField({name: 'field', validate: fn2})
```

1) two sync validations - pass & fail
2) two async validations - pass & fail
3) combine sync and async - pass & fail

**Comment by Hyperkid123** [comment]
@rvsia well turns out I had to re-do the whole validation process because there was an issue with concurrency. But we should have even more powerful validation support right now. We can have unlimited number of async validators with the all-new `composeValidators` function.

**Comment by rvsia** [comment]
@Hyperkid123 

> One downside is that we have run tests with setImmediate to wait for the manager api state update.

Won't be this too huge breaking change for all applications using DDF?

**Comment by Hyperkid123** [comment]
@rvsia yeah it will. What we can do, is first run all the validators, check if there is an async validation and return a promise based on that.

That is an option we probably should and could do. Async validation test must have async-await/setImmediate/timeout anyway.

**Comment by rvsia** [comment]
@Hyperkid123

> What we can do, is first run all the validators, check if there is an async validation and return a promise based on that.

Yeah, sounds good. Run them and just compose async validators. Do you want to do it in this PR?

**Comment by Hyperkid123** [comment]
Yes I will.

**Comment by Hyperkid123** [comment]
@rvsia the compose validators will only return a promise if one or more validators are asynchronous.

**Review by rvsia — APPROVED** [review]

**Pull request merged**
