### PR TITLE
Fix data type validation message for numeric validator in case of custom message

### PR DESCRIPTION
**Pull request by jspannu919**
Currently if have a validation (ex: minimum) on a numeric field and the value is not a number then it shows the data type wrong message (Value must be an integer) and if the type is correct then it shows the correct message (Value must be greater or equal.....). But when we are passing a custom validation message, then the data type message is not displayed and in that case also the custom message is shown.

### CODE REVIEW

**Review by rvsia — APPROVED** [review]
Thank you for this PR! 

Looks good to me, could you please solve the conflict? 😊

**Comment by rvsia** [comment]
@Hyperkid123 the bot is showing that no version will be released.. do you see anything wrong here or is the bot broken? 🤔

**Comment by jspannu919** [comment]
> Thank you for this PR!
> 
> Looks good to me, could you please solve the conflict? 😊

Done. Got conflicts with my own changes ;-)

**Pull request merged**
