### PR TITLE
feat(pf4): Upgrade to PatternFly 6

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
**Description**

Upgrades the pf4-component-mapper PatternFly dependencies to our v6 release

**Checklist:** *(please see [documentation page](https://data-driven-forms.org/development-setup) for more information)*

- [x] `Yarn build` passes
- [x] `Yarn lint` passes
- [x] `Yarn test` passes
- [ ] Test coverage for new code *(if applicable)*
- [ ] Documentation update *(if applicable)*
- [x] Correct commit message
   - format `fix|feat({scope}): {description}`
   - i.e. `fix(pf3): wizard correctly handles next button`
   - fix will release a new \_.\_.X version
   - feat will release a new \_.X.\_ version (use when you introduce new features)
     - we want to avoid any breaking changes, please contact us, if there is no way how to avoid them
   - scope: package
   - if you update the documentation or tests, do not use this format
     - i.e. `Fix button on documenation example page`

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@wise-king-sullyman we will make this a major release. We do have some time still before this is absolutely necessary.

We will also have to do a follow-up and update the Docs code samples templates.

**Comment by wise-king-sullyman** [comment]
@Hyperkid123 is there anything further I need to do on this PR at the moment?

**Comment by Hyperkid123** [comment]
Not right now. I just need some time to go trough all the changes and make sure we get the proper release. I think it can sit here for a bit, we are in no rush just yet. I hope I'll have some time for review in a few days.

**Comment by Hyperkid123** [comment]
@wise-king-sullyman ok, I think there is still some work remaining. Tried running the pf playground and there are some missing CSS errors:
```Module not found: Error: Can't resolve '@patternfly/react-styles/css/components/Select/select.css' in '/Users/martin/ddorg/react-forms/packages/pf4-component-mapper/src/select/select'
```
You can run the playground by switching to the PF component mapper dir and running `yarn start`

**Comment by wise-king-sullyman** [comment]
@Hyperkid123 resolved the errors, but I think I still have some work to do now that I've seen this playground.

It's hard to say for sure though because I tried to pull master and run the playground and compare, and it seems to be missing all of the PF styles? Not sure if that's just a me thing though.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
