### PR TITLE
[V2] Stream line build output files structure.

### PR DESCRIPTION
**Pull request by Hyperkid123**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia I think it's ready. Checking if the docs still works would be a priority probably.

**Comment by Hyperkid123** [comment]
Yeah that is the one thing that I cannot figure out. I wonder if that is only in SSR mode.

**Comment by rvsia** [comment]
@Hyperkid123  so should we merge this?

**Comment by Hyperkid123** [comment]
I don't know. We will have to deal with it later. And we should probably switch to the pf3 version of date time picker.

**Comment by rvsia** [comment]
@Hyperkid123 yeah, let’s merged it, it is still just a beta

**Pull request merged**
