### PR TITLE
feat(layout): makes PF3 forms vertical

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

Makes all form vertical by default.

* removes `COL` component 

WIP because design is not clear.

### Before

image
image
image
image

### After

image
image
image
image

@terezanovotna How should switch/checkboxes/radios look in a vertical form?

cc @martinpovolny @Hyperkid123

### CODE REVIEW

**Comment by terezanovotna** [comment]
First of all, 
awesome job on always including before and after screenshots, thank you for that!

1)Text boxes 👍
2)Switched 👍
3)Checkboxes and radio buttons, let's put each item on new row, which means:

Title text
checkbox text
checkbox text

Title text
Radio text
radio text

**Comment by Hyperkid123** [comment]
> Title text
> checkbox text
> checkbox text

@terezanovotna how do we deal with single checkbox? 

right now its like this:
**label** checkbox

**Comment by rvsia** [comment]
@terezanovotna thanks for answering! :trophy: 

One more thing: what about checkboxes which have only one text? :confused:

**Comment by terezanovotna** [comment]
that's right. I would switch an order. 

Title (if there is one)
checkbox label

**Comment by rvsia** [comment]
@terezanovotna 

image

**Comment by rvsia** [comment]
### Changes in ManageIQ


Before screenshot could be found in PRs: 
Import/Export https://github.com/ManageIQ/manageiq-ui-classic/pull/5180
Catalog https://github.com/ManageIQ/manageiq-ui-classic/pull/5139
Flavor https://github.com/ManageIQ/manageiq-ui-classic/pull/5055
Tenant https://github.com/ManageIQ/manageiq-ui-classic/pull/4895
Ownership https://github.com/ManageIQ/manageiq-ui-classic/pull/5046
Server Relatinship https://github.com/ManageIQ/manageiq-ui-classic/pull/5233
Services edit https://github.com/ManageIQ/manageiq-ui-classic/pull/4985

Screenshot from 2019-04-12 09-59-06
Screenshot from 2019-04-12 09-58-23
Screenshot from 2019-04-12 09-56-32
Screenshot from 2019-04-12 09-54-23
Screenshot from 2019-04-12 09-51-02
Screenshot from 2019-04-12 09-50-14
Screenshot from 2019-04-12 09-49-43

@terezanovotna @martinpovolny @Hyperkid123 

The only ugly change is in the Import/Export form, where it could be fix by just setting a different column size of the text.

**Comment by Hyperkid123** [comment]
@rvsia you want the label to be multi line?

**Comment by terezanovotna** [comment]
not sure I understand @rvsia. Are you talking about this export and import?
Screen Shot 2019-04-12 at 13 28 01

If so, I would make these buttons.  with the text that's in the explanation. thoughts?

**Comment by rvsia** [comment]
@terezanovotna No, about this text:

image

It is now aligned to match horizontal inputs and I just wanted to say that it is easy to align it to right, so you should not worry about that. :smiley:

**Comment by terezanovotna** [comment]
@miq-bot add_label ux/approved

**Comment by rvsia** [comment]
@Hyperkid123  please review :call_me_hand:

**Comment by Hyperkid123** [comment]
@rvsia travis is dead

**Comment by Hyperkid123** [comment]
@rvsia travis died again

**Comment by rvsia** [comment]
@Hyperkid123 Should be OK now, dependencies are changing too fast! :racehorse:

**Comment by martinpovolny** [comment]
Please, ping also @epwinchell in these design and UX related PRs and discussions.

**Pull request merged**
