### PR TITLE
feat(carbon): add dual list component

### PR DESCRIPTION
**Pull request by rvsia**
part of https://github.com/data-driven-forms/react-forms/issues/795

TODO:
- [x] tests
- [x] treeshake carbon react icons

carbonduallist

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia I think we need to clean this up a bit.

- The dimensions of the list change on the hover event (the item gets taller). Can we do something about that?
- We need some spacing between the move buttons
- The move all buttons should be next to each other -> moveRight, moveAllRight, moveAllLeft, moveLeft 
- The dropdown icon looks out of place. Probably should be aligned to the center of the filter input and have more spacing around it. And it does not look like its interactable.
- The middle column should have a bit more spacing from the sides.

**Comment by rvsia** [comment]
Ad 1) it's controlled from Carbon itself.
Ad 2) Ok
Ad 3) Ok
Ad 4) Dropdown icon cannot be aligned, the offset is set in the svg
Ad 5) Ok
Ad 6) Carbon

updated

**Comment by Hyperkid123** [comment]
@rvsia could you also provide a picture of this on smaller screen?

**Comment by rvsia** [comment]
image

**Comment by Hyperkid123** [comment]
@rvsia ok the only mini nitpick I have is that the arrow icons on buttons should also change direction towards the list.

**Comment by rvsia** [comment]
done

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
