### PR TITLE
fix(carbon): combobox initial value label

### LINKED ISSUE #1022: initialValues Display Incorrectly in Select Component with isSearchable Property
**Description:** When trying to set the initialValues for a select component with the `isSearchable` property, the select treats the initialValues as the text to input into the field as opposed to the value of one of the options.

```
<FormRenderer
    schema={schema}
    initialValues={{ test: "test1" }}
    FormTemplate={FormTemplate}
    componentMapper={componentMapper}
    onSubmit={console.log}
/>
...
{
    component: "select",
    name: "test",
    id: "test",
    label: "Select",
    isSearchable: true,
    options: [
        {
          value: "test1",
          label: "This is test 1"
        },
        { value: "test2", label: "This is test 2" },
        { value: "test3", label: "This is test 3" },
        { value: "test4", label: "This is test 4" }
    ]
}
```

With `isSearchable`:

Without:

**Example:** https://stackblitz.com/edit/mtevuf-byqvrw?file=schema.js

### PR DESCRIPTION
**Pull request by Hyperkid123**
fixes #1022 

Will be backported to v2 after merge

### CODE REVIEW

**Review by rvsia — COMMENTED** [review]
Could you please also take a look on `isSearchable`+`simpleValue` variant? Now, combobox returns the whole option object. I am not sure if it is intended or not. 😬

**Comment by Hyperkid123** [comment]
@rvsia id does not return the whole object, just the value. I don't even think simple value exists in carbon components. I believe it always returns just the value from the option.

**Comment by Hyperkid123** [comment]
The simple value was OK. But all other select variants had same/similar issues with the initial value text. I've added accessors to properly create the initial selected prop.

**Comment by rvsia** [comment]
@Hyperkid123 I see an error with this schema:

```jsx
            schema={{
              fields: [
                {
                  component: 'select',
                  name: 'test',
                  id: 'test',
                  label: 'Select',
                  isSearchable: true,
                  simpleValue: true,
                  options: [
                    {
                      value: 'test1',
                      label: 'This is test 1'
                    },
                    { value: 'test2', label: 'This is test 2' },
                    { value: 'test3', label: 'This is test 3' },
                    { value: 'test4', label: 'This is test 4' }
                  ]
                }
              ]
            }}
```

```jsx
select.js:13 Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.onChange (select.js:13)
    at Object.onChange (ComboBox.js:144)
    at Downshift.<anonymous> (downshift.esm.js:681)
```


Kapture 2021-04-06 at 13 34 10

**Comment by rvsia** [comment]
And it does return a whole object

```jsx
            schema={{
              fields: [
                {
                  component: 'select',
                  name: 'test',
                  id: 'test',
                  label: 'Select',
                  isSearchable: true,
                  //simpleValue: true,
                  options: [
                    {
                      value: 'test1',
                      label: 'This is test 1'
                    },
                    { value: 'test2', label: 'This is test 2' },
                    { value: 'test3', label: 'This is test 3' },
                    { value: 'test4', label: 'This is test 4' }
                  ]
                }
              ]
            }}
```

Kapture 2021-04-06 at 13 37 12

**Comment by Hyperkid123** [comment]
> And it does return a whole object

@rvsia that is because the default `simpleValue` is set to false. It is supposed to return the whole object.

**Comment by rvsia** [comment]
@Hyperkid123 Yeah, but normal select returns only the value. We need to make it consistent. (And in multi you can use simpleValue)

**Comment by Hyperkid123** [comment]
I agree. But I can't tell you why it's here. At this point, it could break existing forms.

**Comment by rvsia** [comment]
Yep and that's why we should enable to use simpleValue on isSearchable single select - it won't break anything.

Initially, there was no comboBox and the single select was always returning just the value.. but ComboBox broke this behavior and nobody catched that.

**Comment by Hyperkid123** [comment]
I think we should address it in another issue. Now that I see the code, there are more issues with the component than just simple values, etc. It needs a major clean-up.

I've fixed the onChange crash.

**Review by rvsia — APPROVED** [review]

**Pull request merged**
