### PR TITLE
fix(pf3): stop date picker crash when value is string.

### LINKED ISSUE #189: Opening a datepicker with a preset initialValue crashes
The schema below throws an an `e.getTime is not a function` error:
```javascript
{
  component: componentTypes.DATE_PICKER,
  name: "date-picker-1",
  label: "Datepicker 1",
  initialValue: "2019-11-01T12:31:00.000Z",
  disabledDays: [
    {
      before: "today"
    }
  ],
  variant: "date"
}
```

### PR DESCRIPTION
**Pull request by Hyperkid123**
closes #189 

Day picker can now accept value as a string.

### CODE REVIEW

**Comment by Hyperkid123** [comment]
ups forgot add the WIP thing Working on it right now.

**Comment by skateman** [comment]
Now it's throwing me `Invalid Date` if the `initialValue` is not set:
```json
{
  "component": "date-picker",
  "name": "date-picker-1",
  "label": "Datepicker 1",
  "visible": true,
  "disabledDays": [
    {
      "before": "today"
    }
  ],
  "variant": "date"
}
```

Screenshot from 2019-11-01 10-15-29

And by clicking on the picker icon, it crashes with `Cannot read property 'length' of undefined`

**Comment by Hyperkid123** [comment]
@skateman ah there is one mor thing i forgot

**Comment by rvsia** [comment]
@Hyperkid123 what about to add a test that proves that `picker icon click crash` is gone, just to be sure it won't repeat in the future? Otherwise looks good!

**Comment by Hyperkid123** [comment]
@rvsia the crash has nothing to do with the clicl but with the fact the it was sending string to the day picker component instead of Date object.

**Pull request merged**
