### PR TITLE
Fix typo lenght => length

### PR DESCRIPTION
**Pull request by Fryguy**
@skateman Please review

### CODE REVIEW

**Comment by skateman** [comment]
Umm ... I'm not JS expert and far from having merge rights into this repo, but yeah, I approve

**Comment by skateman** [comment]
@rvsia @Hyperkid123

**Comment by Hyperkid123** [comment]
@Fryguy Thank you. I can image there is going to be a lot more of these.

**Comment by Hyperkid123** [comment]
@Fryguy in order to trigger release can you please use the semantic release commit message format:
```
fix(renderer): Commit message // renderer in brackets because it affects the renderer packages
```

**Comment by Fryguy** [comment]
@Hyperkid123 I don't understand what I'm supposed to do, since I did a general find/replace across the codebase.  What is the renderer? (This is a drive-by PR, so I'm honestly not sure it even needs changelog or anything)

**Comment by rvsia** [comment]
@Fryguy Reword the commit message: `Fix typo lenght => length` to `fix(renderer): Fix typo lenght => length`.


`Fix` will release a new version and `renderer` (react form renderer) is a scope/package of this PR (see https://data-driven-forms.org/renderer/development-setup#commits )

**Pull request merged**
