### PR TITLE
Add MUI dual-list-select component

### PR DESCRIPTION
**Pull request by rvsia**
TODO:
- [x] PF4 dualllist > common
- [x] MUI dual list
- [x] tests
- [x] update demo
- [x] renderer make dual list select constant

example (checkbox variant)

muiduallist

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia I think we should probably use adornments for the icons: https://material-ui.com/components/text-fields/#input-adornments

**Comment by rvsia** [comment]
@Hyperkid123 The input is filtering, the icon is sorting.  Not sure if we should mix these two actions in one input.

**Comment by Hyperkid123** [comment]
:thinking: hmm that icon does not remind me of sorting

**Comment by rvsia** [comment]
@Hyperkid123 It's literally called 'SortIcon' :smile: I can use arrow if you want to.

**Comment by Hyperkid123** [comment]
I know but it just does not seem right to me :smiley:. If you look at the table demo for example, that are using the arrows as well: https://material-ui.com/components/tables/#sorting-amp-selecting

**Comment by rvsia** [comment]
arrow

done

**Pull request merged**
