### PR TITLE
feat(manager): integrate manager with DDF

### PR DESCRIPTION
**Pull request by rvsia**
- [x] update tests
- :stop_sign:  render optimization - do separately
   - :stop_sign:  it seems that registering a lot fields at once is too slow :thinking:
   - :stop_sign: changing values is so slow (try to hold key on textinput)
- [x] subit focus already fixed errors (there is probably key with undefined)

### CODE REVIEW

**Comment by Hyperkid123** [comment]
> it seems that registering a lot fields at once is too slow

I believe that's because is done one by one. We could do it in a batch.

**Comment by Hyperkid123** [comment]
@rvsia what is the performance like?

**Comment by rvsia** [comment]
@Hyperkid123  This is ready for review although:
- a lot of optimization needs to be done
- some PF3 tests are skipped because there will be removed anyways
- some new features are missing test coverage, will be done separately

**Comment by Hyperkid123** [comment]
Ok we will take care of that in different PR

**Comment by rvsia** [comment]
@Hyperkid123 Yeah, this is not intended to be the final PR, but just an initial integration to be able to test it in a real environment. After this is merged, the fun can start! :smile:

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
